name: knowcol
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - comm=0.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - ipykernel=6.28.0
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.13
  - pip=24.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - python=3.10.14
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
    - accelerate==1.4.0
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - altair==5.3.0
    - annotated-types==0.6.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.4.0
    - appdirs==1.4.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.2.0
    - babel==2.15.0
    - beautifulsoup4==4.12.3
    - bitsandbytes==0.45.3
    - bleach==6.1.0
    - blinker==1.8.2
    - blis==0.7.11
    - braceexpand==0.1.7
    - cachetools==5.3.3
    - catalogue==2.0.10
    - certifi==2024.2.2
    - cffi==1.16.0
    - cfgv==3.4.0
    - charset-normalizer==2.0.12
    - click==8.1.7
    - cloudpathlib==0.16.0
    - confection==0.1.4
    - contexttimer==0.3.3
    - contourpy==1.2.1
    - cycler==0.12.1
    - cymem==2.0.8
    - decord==0.6.0
    - defusedxml==0.7.1
    - distlib==0.3.8
    - docker-pycreds==0.4.0
    - easydict==1.13
    - einops==0.8.0
    - exceptiongroup==1.2.1
    - executing==2.0.1
    - fairscale==0.4.4
    - fastjsonschema==2.19.1
    - filelock==3.14.0
    - fonttools==4.51.0
    - fqdn==1.5.1
    - frozenlist==1.4.1
    - fsspec==2024.5.0
    - ftfy==6.2.0
    - gdown==5.2.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - google-api-core==2.19
    - google-api-python-client==2.129
    - google-auth==2.29
    - google-auth-httplib2==0.2
    - googleapis-common-protos==1.63
    - gshell==5.6.1
    - h11==0.14.0
    - httpcore==1.0.5
    - httplib2==0.22.0
    - httpx==0.27.0
    - huggingface-hub==0.29
    - hydra-core==1.3.2
    - identify==2.5.36
    - idna==3.7
    - imageio==2.34.1
    - iopath==0.1.10
    - ipywidgets==8.1.3
    - isoduration==20.11.0
    - jedi==0.19.1
    - jinja2==3.1.4
    - joblib==1.4.2
    - json5==0.9.25
    - jsonlines==4.0.0
    - jsonpointer==2.4
    - jsonschema==4.22.0
    - jsonschema-specifications==2023.12.1
    - jupyter==1.0.0
    - jupyter-console==6.6.3
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.14.1
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.2.1
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.1
    - jupyterlab-widgets==3.0.11
    - kaggle==1.6.12
    - kiwisolver==1.4.5
    - langcodes==3.4.0
    - language-data==1.2.0
    - lazy-loader==0.4
    - lightning==2.2.5
    - lightning-utilities==0.11.2
    - marisa-trie==1.1.1
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.9.0
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - mistune==3.0.2
    - mpmath==1.3.0
    - multidict==6.0.5
    - murmurhash==1.0.10
    - nbclient==0.10.0
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - nodeenv==1.8.0
    - notebook==7.2.0
    - notebook-shim==0.2.4
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.1.105
    - oauth2client==4.1.3
    - omegaconf==2.3.0
    - open-clip-torch==2.24.0
    - opencv-python-headless==4.5.5.64
    - opendatasets==0.1.22
    - overrides==7.7.0
    - packaging==24.0
    - pandas==2.2.2
    - pandocfilters==1.5.1
    - parso==0.8.4
    - pexpect==4.9.0
    - pillow==10.3.0
    - platformdirs==4.2.2
    - plotly==5.22.0
    - portalocker==2.8.2
    - pre-commit==3.7.1
    - preshed==3.0.9
    - prometheus-client==0.20.0
    - proto-plus==1.23.0
    - protobuf==4.25.3
    - pyarrow==16.1.0
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pycocoevalcap==1.2
    - pycocotools==2.0.7
    - pycparser==2.22
    - pydantic==2.7.1
    - pydantic-core==2.18.2
    - pydeck==0.9.1
    - pydrive==1.3.1
    - pygments==2.18.0
    - pyparsing==3.1.2
    - pysocks==1.7.1
    - python-dateutil==2.9.0.post0
    - python-json-logger==2.0.7
    - python-magic==0.4.27
    - python-slugify==8.0.4
    - pytorch-lightning==2.2.5
    - pytz==2024.1
    - pyyaml==6.0.1
    - qtconsole==5.5.2
    - qtpy==2.4.1
    - rank-bm25==0.2.2
    - referencing==0.35.1
    - regex==2024.5.15
    - requests==2.31
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.7.1
    - rpds-py==0.18.1
    - rsa==4.9
    - safetensors==0.4.3
    - scikit-learn==1.5.0
    - scipy==1.13.0
    - send2trash==1.8.3
    - sentence-transformers==3.0.0
    - sentencepiece==0.2.0
    - sentry-sdk==2.7.1
    - setproctitle==1.3.3
    - smart-open==6.4.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - soupsieve==2.5
    - spacy==3.7.4
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - srsly==2.4.8
    - stack-data==0.6.3
    - sympy==1.12
    - tenacity==8.3.0
    - terminado==0.18.1
    - text-unidecode==1.3
    - thinc==8.2.3
    - threadpoolctl==3.5.0
    - tifffile==2024.5.10
    - timm==0.4.12
    - tinycss2==1.3.0
    - tokenizers==0.21.0
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.12.1
    - torch==2.3.0
    - torchmetrics==1.4.0.post0
    - torchvision==0.18.0
    - tornado==6.4
    - tqdm==4.66.4
    - traitlets==5.14.3
    - transformers==4.49.0
    - triton==2.3.0
    - typer==0.9.4
    - types-python-dateutil==2.9.0.20240316
    - typing-extensions==4.11.0
    - tzdata==2024.1
    - uri-template==1.3.0
    - uritemplate==4.1.1
    - urllib3==1.26.20
    - virtualenv==20.26.2
    - wandb==0.16.2
    - wasabi==1.1.2
    - watchdog==4.0.0
    - wcwidth==0.2.13
    - weasel==0.3.4
    - webcolors==1.13
    - webdataset==0.2.86
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - widgetsnbextension==4.0.11
    - yarl==1.9.4
