defaults:
    - callbacks: default
    - datamodule@datamodule1: entity_only
    - datamodule@datamodule2: query_only
    - kg: default
    - model: knowcol
    - trainer: default
    - training: default
    - logger: wandb

seed: 42
log_dir: ./
slurm: false

hydra:
  run:
    dir: ${log_dir}/checkpoints/${now:%Y-%m-%d}/${now:%H-%M-%S}